version: '2'
services:
  postgres-db:
    image: postgres:13
    container_name: db-postgres
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dwh
    volumes:
    - pg_data:/var/lib/postgresql/data
    ports:
    - 5436:5432/tcp
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=sources
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3307:3306/tcp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql_data: # docker volume create mysql_data
    external: true
  pg_data: # docker volume create postgres_data
    external: true

networks:
  my-network:
    external: true
